version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linora
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/linora
      JWT_SECRET: supersecret
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

  # client:
  #   build: ./client
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - server

volumes:
  db-data:
